### PR TITLE
Add dehumidifier function

### PR DESCRIPTION
**Pull request by JyunWei-Su**
Add the following dehumidifier function:
* Fan operation mode select (duplicated, removed)
* Fan direction select
* Set humidity select (duplicated, removed)
* Power control switch (duplicated, removed)
* Buzzer control switch
* NanoeX control switch

### CODE REVIEW

**Comment by osk2** [comment]
Thank you, @JyunWei-Su

I have two questions:
1. Since the humidifier entity already includes power control and operation mode, do we really need separate entities for these functions?
2. Regarding the humidity select entity, should we change the operation mode to manual humidity setting before sending the command?

**Comment by JyunWei-Su** [comment]
1. When I checked the logs, I found that my humidifier entity did not load correctly. I am not sure if this is caused by another bug, so I added two control entities (power control and operation mode) separately.

```
2024-07-13 14:47:53.237 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry *** for humidifier
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 801, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py", line 126, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 202, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
```

2. Regarding the humidity select entity, should we change the operation mode to manual humidity setting before sending the command? **No**, the operation mode will be automatically changed if the humidity select entity value has changed (and the command is sent).

Note: my dehumidifier model is **F-Y20JH**
Core version: 2024.7.2
Supervisor version: 2024.06.2
panasonic smart app version based on 2.8.1

**Comment by JyunWei-Su** [comment]
Hi @osk2 ,
I have fixed the humidifier.py so that it works well. #110 
According to your previous suggestion, I think we DON'T need to separate entities for three functions (fan operation mode select, set humidity select, and power).

**Comment by osk2** [comment]
I'm going to merge this PR and do some testing.
Since I am busy with other things, this could take a while before we can release the new version.

**Pull request merged**
